version: "3.7"
services:
    doccano:
        image: doccano/doccano
        container_name: doccano
        environment:
            ADMIN_USERNAME: "admin"
            ADMIN_PASSWORD: "password"
            ADMIN_EMAIL: "admin@example.com"
        ports:
            - 8000:8000

    spacy-server:
        build: ./spacy-server
        container_name: spacy-server
        environment:
            SPACY_USER: ${SPACY_USER}
            SPACY_PASSWORD: ${SPACY_PASSWORD}
        # https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3
        volumes:
            - ./custom-model/model-best:/model
        ports:
            - 8080:8080
        depends_on:
            - doccano